[tool.poetry]
name = "nlp"
version = "0.1.0"
description = ""
authors = ["cesar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^1.0.1"
prefect = "^2.19.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
